version: '3'
services:
  db:
    image: postgres:13
    restart: always
    container_name: prisma-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: infoteam_subject
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    build: .
    container_name: infoteam-advanced-subject
    ports:
      - '3000:3000'
    depends_on:
      - db
      - push-server
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/infoteam_subject
      - JWT_SECRET=${JWT_SECRET}
      - PUSH_SERVER=http://push-server:8090/api/push
    networks:
      - app-network

  push-server:
    image: yeonhyukkim/fake-push-server:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
